/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ws3d_hub;

import ws3d_hub.CreatureController;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;
import ws3dproxy.CommandExecException;

/**
 *
 * @author Note Fabio M
 */
public class frame_HubHome extends JFrame implements KeyListener {

    @Override
    public void keyPressed(KeyEvent e) {
        try {
            if (e.getKeyCode() == KeyEvent.VK_UP) {
                //creature.start();
                //creature.updateState();
                //creature.move(2.0, 2.0, 5.0);
            } 
            else if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                //creature.start();
                //creature.updateState();
                //creature.move(-2.0, -2.0, 5.0);
            }
        }
        catch (Exception ex) {
            System.out.println("Socket Error. " + ex.getMessage());
        }
    }
    
    @Override
    public void keyReleased(KeyEvent e) {
        //try {
            //creature.stop();
        //} catch (CommandExecException ex) {
        //    System.out.println("Socket Error. " + ex.getMessage());
        //}

    }
    
    @Override
    public void keyTyped(KeyEvent e) {
        System.out.println("keyTyped = " + e.getKeyChar());
    }
  
    
    /**
     * Creates new form frame_HubHome
     */
    

    public static void execute() {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                frame_HubHome frame = new frame_HubHome();
                frame.setTitle(".: HUB - ws3d :.");
                frame.setResizable(false);
                frame.setSize(600, 400);
                frame.setMinimumSize(new Dimension(600, 400));
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
                
                CreatureController cc = new CreatureController();
            }
        });
    }
    
    frame_HubHome() {
        addKeyListener(this);
        //setFocusable(true);
        //setFocusTraversalKeysEnabled(false);
        initComponents();
    }
    
   
  
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
